### ISSUE TITLE
Change add-on name from `Extract 'Em!` to `Attachment Extractor`

### ISSUE THREAD

**Issue by ovari** [tmccoid-tech/extract-em#14]
`'Em` could refer many things, such as "email addresses" and "display names".

Should the name be improved to be more explicit, such as changing the name from `Extract 'Em!` to `Attachment Extractor`?

It might make it easier for people to find your add-on on [ATN](https://addons.thunderbird.net/).

Thank you

**Comment by ThunderbirdMailDE** [comment]
@jobisoft
From my point of view, the author of this add-on is welcome to take over my old ATN addon entries or it can be forwarded accordingly.

What can be done that makes sense?

**Comment by jobisoft** [comment]
Best would be to sunset your own add-on:
* release a final version which informs users about it being discontinued
* the info page can have a button to the ATN page of this add-on and suggest Extract'em! as an alternative

Check out DAV-4-TbSync 4.8:
https://addons.thunderbird.net/addon/dav-4-tbsync/versions/

**Comment by tmccoid-tech** [comment]
Closing

**Comment by ThunderbirdMailDE** [comment]
No interest, no action.
