### ISSUE TITLE
After downloading i can only "Close" vs "Close & Exit" but not "Detach & delete"

### ISSUE THREAD

**Issue by ell1e** [tmccoid-tech/extract-em#15]
After downloading and generating report (amazing functionality!) i can apparently only "Close" vs "Close & Exit" but not e.g. "Detach & delete". Basically, after fetching all the attachments, I would now like to delete the ones it gave me from the server and only keep the local backup with the report  i just saved. But it's not obvious what button I should be pressing for that, it doesn't seem to be possible even though I assume somehow it is. I also don't understand how "Close" vs "Close & Exit" is any different, maybe it's just me though, or perhaps a better naming could be found?

Sorry if I'm just being confused and I'm just clicking the wrong buttons, it has happened :pensive: it's a really cool addon.

**Comment by tmccoid-tech** [comment]
Hi,

The "Permanently Detach" feature (basically deletion of extracted attachments from the source message) will only be broadly available once the next major version of Thunderbird (I believe it will be 128) is released.  Fortunately, that release should be in the very near future although I can't give you an exact date.

I am assuming you are using the latest version of Thunderbird (115.*); if you are instead using a development version (117+) please let me know that version number.

The distinction between Close and Close & Exit is that C&E exits the extension entirely, where as Close simply closes the discovery/extraction panel and returns you to the Main Menu or the "Let Me Choose" screen.

I'm glad you are enjoying Extract 'Em!  If you have the time and inclination, I would appreciate a review and a rating of the extension.

Let me know if I can be of further assistance.

Regards,
Tom

**Comment by tmccoid-tech** [comment]
You certainly can!  The latest beta version (128 b6 as of yesterday) supports the Permanently Detach feature.

One thing to keep in mind if you go this route is you will not be upgrading from 115 to 128b but installing the beta version side-by-side, meaning that the profile (accounts and settings and so forth) you currently have set up in 115 will not be automatically applied to 128b; they will need to be imported.
