### ISSUE TITLE
Only delete attachments possible?

### ISSUE THREAD

**Issue by Martin511** [tmccoid-tech/extract-em#21]
Sorry, this is not an issue but I didn´t find a "Discussions" section here.
I just want to know if it is possible to only _delete_ attachments without saving them.
I read the Wiki but it is not clear for me.

Regards
Martin

**Comment by tmccoid-tech** [comment]
Hi Martin,

I am afraid that a pure delete feature is not available in this extension.

Tom

**Comment by xjustbmw** [comment]
i am also interested in this feature to skip archiving (just delete), we have very old emails with .pdf manuals that are huge(duplicate as well). a selection by filetype + size would be also amazing (ie: only delete big attachment files)

thank you
