### ISSUE TITLE
Unselect all files in Attachment List

### ISSUE THREAD

**Issue by jbrokamp** [tmccoid-tech/extract-em#26]
Hi, very useful add-on!

I downloaded all files in a folder, but now I just want to download the ones I didn't download before. Using the Discover Attachments button I get a list of all attachments, which is useful. My issue is that they're all selected, when I only need 10 out of 400. I would like to click 10 times, instead of 390.

How about a (Un)select All button? I can contribute, make a PR, if you think the idea fits this project.

**Comment by tmccoid-tech** [comment]
This is a sensible request.  I have a release planned for sometime next week, and I should be able to include this feature in that release.

**Comment by tmccoid-tech** [comment]
Extract 'Em! 1.4.5 has now been released and it includes a "master" checkbox as you requested.  It is located in the Attachment List header next to the selection count label.

If you would be so kind I would appreciate a rating on the extension.  In any event, I hope you continue to enjoy using Extract 'Em!

**Comment by jbrokamp** [comment]
Great, it works as requested :) Did the review as well. Cheers
